from enum import Enum

class Status(str, Enum):
    CANCELED = "CANCELED"
    PROCESSING = "PROCESSING"
    REQUIRES_ACTION = "REQUIRES_ACTION"
    REQUIRES_CAPTURE = "REQUIRES_CAPTURE"
    REQUIRES_CONFIRMATION = "REQUIRES_CONFIRMATION"
    REQUIRES_PAYMENT_METHOD = "REQUIRES_PAYMENT_METHOD"
    SUCCEEDED = "SUCCEEDED"
