services:
  divvy-db:
    image: postgres:16
    ports:
      - "5601:5432"
    environment:
      POSTGRES_DB: divvy-db
      POSTGRES_USER: divvy
      POSTGRES_PASSWORD: divvy
    volumes:
      - divvy_data:/var/lib/postgresql/data
    networks:
      - divvy-network


  minio:
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: divvyminio
      MINIO_ROOT_PASSWORD: divvyminio
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      retries: 5
    networks:
      - divvy-network


  divvy-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - divvy-db
      - minio
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    networks:
      - divvy-network


volumes:
  divvy_data:
  minio_data:

networks:
  divvy-network:
