from app.routers.auth import router as auth_router
from app.routers.test_table import router as test_table_router
from app.routers.group import router as group_router
from app.routers.user_group import router as user_group_router
from app.routers.group_expense import router as group_expense_router
from app.routers.expense_split import router as expense_split_router
from app.routers.group_media import router as group_media_router
from app.routers.minio import router as minio_router
from app.routers.virtual_card import router as virtual_card_router
from app.routers.extract_receipt import router as scan_receipt
