"""change card number max value

Revision ID: 56a56ed039c5
Revises: b9c775b1e86f
Create Date: 2026-04-09 09:30:22.350212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a56ed039c5'
down_revision: Union[str, Sequence[str], None] = 'b9c775b1e86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('virtual_cards', 'card_number',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('virtual_cards', 'card_number',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
