"""add is_active to user_group

Revision ID: a27e7f3335a5
Revises: 9a6f2c1b4d10
Create Date: 2026-03-07 11:29:37.490610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27e7f3335a5'
down_revision: Union[str, Sequence[str], None] = '9a6f2c1b4d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_groups', 'is_active')
    # ### end Alembic commands ###
