"""add EXTRACT type to action type, make cascade on delete for group model related models

Revision ID: a91373014d5c
Revises: e42aa4821bfa
Create Date: 2026-04-29 15:57:06.610103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91373014d5c'
down_revision: Union[str, Sequence[str], None] = 'e42aa4821bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE action_type ADD VALUE 'EXTRACT'")
    op.drop_constraint(op.f('expense_splits_group_expense_id_fkey'), 'expense_splits', type_='foreignkey')
    op.create_foreign_key(None, 'expense_splits', 'group_expenses', ['group_expense_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('group_expenses_group_id_fkey'), 'group_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'group_expenses', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('group_media_group_id_fkey'), 'group_media', type_='foreignkey')
    op.drop_constraint(op.f('group_media_expense_id_fkey'), 'group_media', type_='foreignkey')
    op.create_foreign_key(None, 'group_media', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_media', 'group_expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('item_splits_item_id_fkey'), 'item_splits', type_='foreignkey')
    op.create_foreign_key(None, 'item_splits', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('items_group_expense_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'group_expenses', ['group_expense_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_groups_group_id_fkey'), 'user_groups', type_='foreignkey')
    op.create_foreign_key(None, 'user_groups', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.create_foreign_key(op.f('user_groups_group_id_fkey'), 'user_groups', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_group_expense_id_fkey'), 'items', 'group_expenses', ['group_expense_id'], ['id'])
    op.drop_constraint(None, 'item_splits', type_='foreignkey')
    op.create_foreign_key(op.f('item_splits_item_id_fkey'), 'item_splits', 'items', ['item_id'], ['id'])
    op.drop_constraint(None, 'group_media', type_='foreignkey')
    op.drop_constraint(None, 'group_media', type_='foreignkey')
    op.create_foreign_key(op.f('group_media_expense_id_fkey'), 'group_media', 'group_expenses', ['expense_id'], ['id'])
    op.create_foreign_key(op.f('group_media_group_id_fkey'), 'group_media', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'group_expenses', type_='foreignkey')
    op.create_foreign_key(op.f('group_expenses_group_id_fkey'), 'group_expenses', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'expense_splits', type_='foreignkey')
    op.create_foreign_key(op.f('expense_splits_group_expense_id_fkey'), 'expense_splits', 'group_expenses', ['group_expense_id'], ['id'])
    # ### end Alembic commands ###
