"""add virtual_card, stripe_transaction tables

Revision ID: b9c775b1e86f
Revises: cbb5886b405b
Create Date: 2026-04-06 06:08:41.650782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b9c775b1e86f'
down_revision: Union[str, Sequence[str], None] = 'cbb5886b405b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    transaction_type_enum = postgresql.ENUM(
        'DEPOSIT', 'PAYMENT', 'REFUND', name='transaction_type', create_type=False
    )
    transaction_status_enum = postgresql.ENUM(
        'SUCCEEDED', 'PENDING', 'FAILED', name='transaction_status', create_type=False
    )
    currency_enum = postgresql.ENUM(
        'USD', 'EUR', 'KZT', 'JPY', 'CNY', 'RUB',
        name='currency',
        create_type=False,
    )

    transaction_type_enum.create(bind, checkfirst=True)
    transaction_status_enum.create(bind, checkfirst=True)

    # Existing "currency" enum was introduced in an earlier migration.
    # Extend it with values needed by the current app enum.
    with op.get_context().autocommit_block():
        for value in ('KZT', 'JPY', 'CNY', 'RUB'):
            op.execute(
                sa.text(
                    f"""
                    DO $$
                    BEGIN
                        BEGIN
                            ALTER TYPE currency ADD VALUE '{value}';
                        EXCEPTION
                            WHEN duplicate_object THEN NULL;
                        END;
                    END
                    $$;
                    """
                )
            )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=False),
    sa.Column('stripe_payment_method_id', sa.String(length=128), nullable=False),
    sa.Column('card_number', sa.String(length=14), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=False),
    sa.Column('card_exp_month', sa.Integer(), nullable=False),
    sa.Column('card_exp_year', sa.Integer(), nullable=False),
    sa.Column('card_brand', sa.String(length=64), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_table('stripe_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=128), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=128), nullable=True),
    sa.Column('type', transaction_type_enum, nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', currency_enum, nullable=False),
    sa.Column('status', transaction_status_enum, nullable=False),
    sa.Column('split_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['virtual_cards.id'], ),
    sa.ForeignKeyConstraint(['split_id'], ['expense_splits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_transactions')
    op.drop_table('virtual_cards')
    postgresql.ENUM(
        'SUCCEEDED', 'PENDING', 'FAILED', name='transaction_status'
    ).drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(
        'DEPOSIT', 'PAYMENT', 'REFUND', name='transaction_type'
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
