"""add total amount and timestamp attributes

Revision ID: d15ce5338985
Revises: 67474315c695
Create Date: 2026-03-06 16:27:48.156577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd15ce5338985'
down_revision: Union[str, Sequence[str], None] = '67474315c695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_splits', sa.Column('last_modified_at', sa.DateTime(), nullable=True))
    op.add_column('group_expenses', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('group_expenses', sa.Column('last_modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_expenses', 'last_modified_at')
    op.drop_column('group_expenses', 'total_amount')
    op.drop_column('expense_splits', 'last_modified_at')
    # ### end Alembic commands ###
